### PR TITLE
Don't quote LIBS arguments

### PR DESCRIPTION
**Pull request by vadi2**
Fix https://github.com/frankosterfeld/qtkeychain/issues/148.

### CODE REVIEW

**Comment by vadi2** [comment]
Oops, sorry for the lack of description in the PR, I actually opened it in the wrong repository - was testing the fix our own first.

The issue I ran into is that qmake with Qt 5.13.1 compiling is broken, when it worked OK with 5.13.0, see https://bugreports.qt.io/browse/QTBUG-78150. I'm testing to see if quotes fix the problem, the build is ongoing at https://travis-ci.com/Mudlet/Mudlet/jobs/232620856.

**Comment by frankosterfeld** [comment]
@vadi2 the fix looks correct either way - thanks. If this fixes it, then I fear the worst for QMake projects out there... I didn't expect such a behavioral change as this point in QMake's life cycle...

**Comment by vadi2** [comment]
Yep, it did fix it. I agree with you about the problem! I'll mention that in the Qt bugtracker.

**Comment by keneanung** [comment]
This should fix #148 btw.

**Comment by vadi2** [comment]
@frankosterfeld would you mind merging this in? thx!

**Pull request merged**
