### PR TITLE
Fix the deploy issue from windeployqt by changing target name.

### PR DESCRIPTION
**Pull request by julonexus**
Hi
That is a proposition to fix the error coming from windeployqt where it tries to search the library inside Qt folders.
"Btw, windeployqt doesn't work when qt5keychain is installed into different prefix, but it's a topic for another report.", already reported at https://github.com/frankosterfeld/qtkeychain/issues/109

From the observation, I guessed that its rules are based on the name (ie: QtxName are a Qt library and need to be find inside Qt folders).
The patch allows to change the name of QtKeychain from Qt5Keychain/Qt6Keychain into a custom one (For example, I'm using it with EQt5Keychain for Linphone)

### CODE REVIEW

**Comment by frankosterfeld** [comment]
Thanks!

**Comment by jlskuz** [comment]
This does not only make the name customizable it changes the former default of lower-case `qt6keychang` to `Qt6Keychain`. This is a breaking change as imports like `#import <qt6keychain/keychain.h>` do not work anymore. Is this intended to be breaking (ie. one should adjust downstream) or not?

**Comment by Montel** [comment]
Hi, Indeed it's broken. 
I can't build pim* with kdesrcbuild
I think that patch is not good here.
Regards

**Comment by nicolasfella** [comment]
Proposal to revert this until it can be fixed properly since it breaks consumer builds: https://github.com/frankosterfeld/qtkeychain/pull/229

**Pull request merged**
