### PR TITLE
Added option to compile translations into library.

### PR DESCRIPTION
**Pull request by akallabeth**
Compile translations as `qrc` resouce into the library

### CODE REVIEW

**Comment by kloczek** [comment]
Better would be move to gettext.

**Comment by frankosterfeld** [comment]
@kloczek that's not a dependency I'd want for Windows/Macos/iOS/Android

**Comment by frankosterfeld** [comment]
Sorry for the long long delay, if you rebase on the lastest master, I'd merge it.

**Comment by akallabeth** [comment]
@frankosterfeld ok, done.

**Pull request merged**
