### PR TITLE
CMake: add deprecation warning for QTKEYCHAIN_STATIC

### PR DESCRIPTION
**Pull request by Be-ing**
The default for the old QTKEYCHAIN_STATIC variable was OFF, which
is effectively the same as the new default BUILD_SHARED_LIBS=ON,
so there is no need to warn in that case.

### CODE REVIEW

**Review by KitsuneRal — APPROVED** [review]
Thanks, that should be good enough.

**Comment by Be-ing** [comment]
Thanks for the quick merge. Could you tag a new release so I can simplify the packaging scripts in vcpkg?

**Comment by frankosterfeld** [comment]
@Be-ing done

**Comment by Be-ing** [comment]
Thanks, here is the PR to update vcpkg: https://github.com/microsoft/vcpkg/pull/21529

**Pull request merged**
