### PR TITLE
Added libsecret support.

### LINKED ISSUE #45: Does not check for gnome-keyring when running in KDE
It did work in 0.3, but stopped in 0.4

I can workaround that bug, by overriding the XDG_CURRENT_DESKTOP environment variable

```
XDG_CURRENT_DESKTOP=GNOME owncloud
```

### LINKED ISSUE #55: Add support for GNOME Keyring 3.18
Apparently, QTKeychain does not currently support GNOME 3.18's keyring. When starting ownCloud's client, the following error appears:

> Reading from the keychain failed and generated this error: "No keychain service available"

and requests entering the password manually. Also, when running from the terminal, the following additional error appears:

> Gkr-Message: secret service operation failed: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

The possible cause is that GNOME 3.18 changed the API, therefore QTKeychain requires to update the access.

### PR DESCRIPTION
**Pull request by akallabeth**
- Fixes #55, #37 
- May fix #45

### CODE REVIEW

**Comment by akallabeth** [comment]
@frankosterfeld Added the missing files, does it work for you now?

**Comment by frankosterfeld** [comment]
Looks good, will test a bit hopefully soon... Which KDE/Gnome versions did you develop/test against?

**Comment by akallabeth** [comment]
@frankosterfeld Currently using debian jessie with backports enabled, so quite old ;)

**Comment by jowi24** [comment]
I applied this patch to my qtkeychain 0.7.0 running on ArchLinux. It works out-of-the box. Great work! Should be included soon in the main source.

**Comment by Patagonicus** [comment]
I've just used this patch to get owncloud-client working with gnome-keyring on Gentoo (with i3 as my window manager). Are there any plans to merge this and do a new release any time soon?

**Comment by frankosterfeld** [comment]
Rebased and merged, thanks!

**Pull request closed without merging**
