### PR TITLE
QMake: Add missing KEYCHAIN_DBUS define

### LINKED ISSUE #182: QMake builds now broken
Something seems amiss in the qmake side of things - given that we use qtkeychain in https://github.com/Mudlet/Mudlet.git and we support both build systems this is a problem for us. The breakage seems to have occurred in the commit: cbc626edcd4920704f74d271acc1fd6dac508b2e .

### PR DESCRIPTION
**Pull request by frankosterfeld**
Fixes #182

### CODE REVIEW

**Comment by frankosterfeld** [comment]
@mmuman Can you test if this fixes the issue for you?

**Comment by mmuman** [comment]
Hmm here on Linux it goes further: it compiles, while without the patch it just failed with missing DBus defines, but instead fails at linking:

```
$ LANG=C make
x86_64-linux-gnu-g++ -Wl,-O1 -o qt5keychain keychain.o keychain_unix.o plaintextstore.o gnomekeyring.o libsecret.o moc_keychain_p.o moc_keychain.o moc_gnomekeyring_p.o kwallet_interface.o moc_kwallet_interface.o   -lsecret-1 -lgio-2.0 -lgobject-2.0 -lglib-2.0 /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5DBus.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:182: qt5keychain] Error 1
```

Possibly because of newer compiler or linker (I'm on Debian Sid). I can try to investigate but not this week, I'm busy with FOSDEM preparations. If it works for you…

As for Haiku, I get an error `cannot run compiler 'g++'` in both cases. But I don't use qmake in the recipe anyway, I probably thought it was deprecated or something, it's not even documented in the wiki…

**Comment by frankosterfeld** [comment]
@mmuman hmm, the .pri doesn't build a separate lib, it is for inclusion in a qmake project, via `include(qt5keychain.pri)`. For building as a separate library, the idea is to use CMake. (Aren't you using CMake in your project anyway?)

**Comment by mmuman** [comment]
Ah ok, then I guess it makes sense it searches for `main` :smile: 
You mean in owncloud client ? I think it just searches for it as an external library; don't remember if it uses qmake or cmake.

**Comment by frankosterfeld** [comment]
Ah, I guess I confused mudlet and owncloud client :D

**Comment by SlySven** [comment]
> @mmuman hmm, the .pri doesn't build a separate lib, it is for inclusion in a qmake project, via include(qt5keychain.pri). For building as a separate library, the idea is to use CMake. (Aren't you using CMake in your project anyway?)

There is a mixup there  - it is the **[Mudlet](https://github.com/Mudlet/Mudlet.git)** project that builds it's own copy of `qtkeychain` if the target system does not have it's own (up to date) copy of the library - and which supports both CMake and QMake build-systems. CMake may be the preferred system nowadays but the integration with Qt still has some sharp/rough edges that mean QMake is still more attractive/fairs better in *some* cases...

**Pull request merged**
