### PR TITLE
CMake: replace QTKEYCHAIN_STATIC with standard BUILD_SHARED_LIBS

### PR DESCRIPTION
**Pull request by Be-ing**
BUILD_SHARED_LIBS is the standard CMake variable for controlling
whether libraries are built dynamically or statically. Using a
nonstandard variable requires extra work for packagers.

https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html

### CODE REVIEW

**Comment by frankosterfeld** [comment]
Thanks!

**Comment by KitsuneRal** [comment]
That doesn't make for a quite smooth transition... though I appreciate that a new QtKeychain version has just been tagged. The issue occurs when I already have `QTKEYCHAIN_STATIC=ON` and, respectively, no `BUILD_SHARED_LIBS` defined at all (which corresponds to static builds by default, though, as the CMake documentation says, some projects may introduce `option()` in a way it's done here) - in such configuration, Qt Keychain now suddenly switches to building a shared object, and I need to explicitly define `BUILD_SHARED_LIBS=OFF` to override that. Note also, that building shared objects might be of limited benefit on Windows and Mac, unless you're doing a vcpkg/framework kind of thing; if you just add up this quite small library to your project, it makes sense to link it statically. Would be great to at the very least issue a warning (even better - override `BUILD_SHARED_LIBS` option to `OFF`) when discovering `QTKEYCHAIN_STATIC` set to `ON`. And separately, also reconsider how much `BUILD_SHARED_LIBS=ON` is a good universal default.

**Comment by frankosterfeld** [comment]
True, the best solution would be to respect both, at least for a transition period.

**Comment by Be-ing** [comment]
or warn if QTKEYCHAIN_STATIC is set

**Comment by Be-ing** [comment]
Follow up: #205

**Pull request merged**
